version: '3'
services:
    confluence:
        image: "atlassian/confluence-server"
        volumes: 
            - ./atlassian-agent.jar:/var/atlassia/atlassian-agent.jar
            - ./mysql-connector-java-8.0.22.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.22.jar
            - ~/your-confluence-home:/var/atlassian/application-data/confluence
        env_file:
            - ./.env
        ports: 
            - "8090:8090"
        restart: always
